import { ApiClient, DefaultApi } from "@anansi-lineage/anansi-sdk";
export function getApiClient (){
    var apiClient = new ApiClient();
 apiClient.basePath = "https://datalineage2.azurewebsites.net";
 apiClient.authentications["JWT"].apiKey = "eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiIzOTAwZDZkYy04ZDRhLTQyNDYtOTNjMi1iYzdjYmEzZWY4MzkiLCJuYW1lIjoiU3dhdGhpIiwiZW1haWxzIjpbInN3YXRoaS5zQHN1a2V0YS5pbiJdLCJ0ZnAiOiJCMkNfMV9zaWdudXBfc2lnbmluIiwibm9uY2UiOiIxIiwic2NwIjoicmVhZCIsImF6cCI6ImM5MGZlZDIxLWIzOGEtNDlkNy04MTY2LTkzMGVlODdmMWIyZSIsInZlciI6IjEuMCIsImlhdCI6MTcxNTg3MjQwNiwiYXVkIjoiYzkwZmVkMjEtYjM4YS00OWQ3LTgxNjYtOTMwZWU4N2YxYjJlIiwiZXhwIjoxNzE1ODc2MDA2LCJpc3MiOiJodHRwczovL2FuYW5zaWh1Yi5iMmNsb2dpbi5jb20vOGVjMTg5ZGYtN2QxNi00MDY0LWEwMmUtNWZhNjNiNjUxYTNmL3YyLjAvIiwibmJmIjoxNzE1ODcyNDA2fQ.mgu7QHw29XxQFbBOLzF7BzAPJu2nER1OZY_fur6W7ngRhl28TZKIVgoQkltGiyGxiP9FKjRe022yJMeLN24RkqnUfVemdCpYw3BWesw69BCKQTdw09cqP8WZcpLDbZwzpNgTORGII15qYhjsU_cW9zZfuLf0s15Xh1N2qlIu63dk48juzOWOym9fs5aTp3Eka3WFT2wlAnT4jqSbkbFl9A1aehLtwYUnjbALqiPlEpGAWiFN6ybrr3DuHzoHZ7qQHjkZH3J-VeKI7YsmR7scpadOGo8ny2AoyJbGY9nW6vQ1T1B7w_HFdToJmJXOuAdp4nv1am2OGfMJgw8ZUDJjlA"; // Update with your API key
 apiClient.authentications["JWT"].apiKeyPrefix = "Bearer";
 const defaultClient = new DefaultApi(apiClient);
 return defaultClient
}