import { ApiClient, DefaultApi } from "@anansi-lineage/anansi-sdk";
export function getApiClient (){
    var apiClient = new ApiClient();
 apiClient.basePath = "https://datalineage2.azurewebsites.net";
 apiClient.authentications["JWT"].apiKey = "eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiIzOTAwZDZkYy04ZDRhLTQyNDYtOTNjMi1iYzdjYmEzZWY4MzkiLCJuYW1lIjoiU3dhdGhpIiwiZW1haWxzIjpbInN3YXRoaS5zQHN1a2V0YS5pbiJdLCJ0ZnAiOiJCMkNfMV9zaWdudXBfc2lnbmluIiwibm9uY2UiOiIxIiwic2NwIjoicmVhZCIsImF6cCI6ImM5MGZlZDIxLWIzOGEtNDlkNy04MTY2LTkzMGVlODdmMWIyZSIsInZlciI6IjEuMCIsImlhdCI6MTcxNTg2OTc1NywiYXVkIjoiYzkwZmVkMjEtYjM4YS00OWQ3LTgxNjYtOTMwZWU4N2YxYjJlIiwiZXhwIjoxNzE1ODczMzU3LCJpc3MiOiJodHRwczovL2FuYW5zaWh1Yi5iMmNsb2dpbi5jb20vOGVjMTg5ZGYtN2QxNi00MDY0LWEwMmUtNWZhNjNiNjUxYTNmL3YyLjAvIiwibmJmIjoxNzE1ODY5NzU3fQ.r99MKItcgk4ETVSrZ5M7qd4rl5z3dArs9sSM2kR1UYDe_p-jkFPM69IJzs0FzX111OTX3W3OUe3pf3hlLmdGbmC2pGKHFPRyTkSUFZfTNAb1FnjgGqoEj-d9Eb4XltP0ZYCRDLhwK03on-glEa_prd3PH6Eao_39rIBQo2Jhm_XHQXWoSQi6qjC_7UO3_kRlNeRaBD4vnnyO-ZV6bUSPsS4XDvKmXdz7kAzqAAS1TahX6Xol6w85MS77cSB1dMtCiLIsqZENABEPTKZ-HVv9gj72zqzhwINhSoI5a7MF8PR7wEX80OkbJ0UyrVnAdysGDOi3E1S7YWDmaW4oPjFhYw"; // Update with your API key
 apiClient.authentications["JWT"].apiKeyPrefix = "Bearer";
 const defaultClient = new DefaultApi(apiClient);
 return defaultClient
}